### ISSUE TITLE
Adjust build server to publish PowerShell module also to PowerShellGallery

### ISSUE THREAD

**Issue by dfch** [dfensgmbh/biz.dfch.PS.Appclusive.Client#34]
Currently our modules are published to NuGet which is not really meant for PowerShell modules and scripts.

Recently Microsoft defined `PackageManagement` (aka *OneGet*) to be the official place for PowerShell scripts.

I already once uploaded a module to it (see [biz.dfch.PS.System.Logging](https://www.powershellgallery.com/packages/biz.dfch.PS.System.Logging/1.1.4.20151222)). I would like TC to automatically publish to this place as well.

And if this is done, we should do this for the other PoSH modules as well.

**TODOs**

* Adjust `.psd1` of 
  * [x] [biz.dfch.PS.Appclusive.Client](https://github.com/dfensgmbh/biz.dfch.PS.Appclusive.Client)
  * [x] [biz.dfch.PS.Abiquo.Client](https://github.com/dfensgmbh/biz.dfch.PS.Abiquo.Client)
  * [x] [biz.dfch.PS.Activiti.Client](https://github.com/dfensgmbh/biz.dfch.PS.Activiti.Client)
  * [x] [biz.dfch.PS.Azure.ServiceBus.Client](https://github.com/dfensgmbh/biz.dfch.PS.Azure.ServiceBus.Client)
  * [x] [biz.dfch.PS.Azure.ServiceBus.Management](https://github.com/dfensgmbh/biz.dfch.PS.Azure.ServiceBus.Management)
  * [x] [biz.dfch.PS.Cimi.Client](https://github.com/dfensgmbh/biz.dfch.PS.Cimi.Client)
  * [x] [biz.dfch.PS.Git.Client](https://github.com/dfensgmbh/biz.dfch.PS.Git.Client)
  * [x] [biz.dfch.PS.Redmine.Client](https://github.com/dfensgmbh/biz.dfch.PS.Redmine.Client)
* Add PowerShellGallery publish job to release job of 
  * [x] [biz.dfch.PS.Appclusive.Client](https://github.com/dfensgmbh/biz.dfch.PS.Appclusive.Client)
  * [x] [biz.dfch.PS.Abiquo.Client](https://github.com/dfensgmbh/biz.dfch.PS.Abiquo.Client)
  * [x] [biz.dfch.PS.Activiti.Client](https://github.com/dfensgmbh/biz.dfch.PS.Activiti.Client)
  * [x] [biz.dfch.PS.Azure.ServiceBus.Client](https://github.com/dfensgmbh/biz.dfch.PS.Azure.ServiceBus.Client)
  * [x] [biz.dfch.PS.Azure.ServiceBus.Management](https://github.com/dfensgmbh/biz.dfch.PS.Azure.ServiceBus.Management)
  * [x] [biz.dfch.PS.Cimi.Client](https://github.com/dfensgmbh/biz.dfch.PS.Cimi.Client)
  * [x] [biz.dfch.PS.Git.Client](https://github.com/dfensgmbh/biz.dfch.PS.Git.Client)
  * [x] [biz.dfch.PS.Redmine.Client](https://github.com/dfensgmbh/biz.dfch.PS.Redmine.Client)

**Comment by rufer7** [comment]
@dfch to what platform should we publish additionally? To do that I need to have an access key for the corresponding platform

**Comment by dfch** [comment]
sorry for not being precise enough - we want to publish the modules to the *PowerShellGallery*, which is the new default package management store for Windows, aka `PackageManagement`, aka `OneGet`

**Comment by rufer7** [comment]
@dfch I tried to publish the nuget package that gets already created by the build server directly to the `Power Shell Gallery` but this didn't work as expected.

```
[14:25:59][push] Registered additional extensions from paths: C:\TeamCity\buildAgent\plugins\nuget-agent\bin\plugins-2.8
[14:25:59][push] Starting NuGet.exe 2.8.60717.93 from C:\TeamCity\buildAgent\tools\NuGet.CommandLine.DEFAULT\tools\NuGet.exe
[14:25:59][push] Pushing biz.dfch.PS.Appclusive.Client 4.4.1 to 'https://www.powershellgallery.com/'...
[14:26:00][push] Failed to process request. 'The item you are trying to publish does not contain a valid module manifest or script file. Check that your Nuget package is correct and try publishing again.'. 
[14:26:00][push] The remote server returned an error: (500) Internal Server Error..
[14:26:00][push] Process exited with code 1
```

Furthermore I tried to use the Cmdlet described [here](https://www.powershellgallery.com/packages/upload) to publish with TeamCity but this is not working as these Cmdlet only allows publishing an installed module and on TeamCity the module is not installed. I did not yet find a working solution for that...

**Comment by dfch** [comment]
@rufer7 strange we get an `HTTP 500` ... but what about this (all on TC)?

1. we *build* the nuspec with TC as usual
1. we rename the nupkg to zip
1. we extract the zip to an arbitrary location
1. we install the module inside zip as if we installed it locally
1. we publish it with `Publish-Module` as you already tried out

**Comment by dfch** [comment]
@ruer7 update on my previous comment: 

I created a working script with which I published three modules

``` powershell
$nuGetApiKey = "tralala"

$nupkg = 'biz.dfch.PS.Appclusive.Client.4.4.1.nupkg'
copy $nupkg $ENV:TEMP
Push-Location $ENV:TEMP
$zip = '{0}.zip' -f $nupkg
Rename-Item $nupkg $zip
Expand-Archive $zip
Push-Location $nupkg
[xml] $nuspecxml = Get-Content -Raw (Get-ChildItem *.nuspec -File | Select -First 1)

Push-Location tools
$psd1 = (Get-ChildItem *.psd1 -File | Select -First 1).FullName

$module = Get-Module $psd1 -ListAvailable;
$module | Publish-Module `
  -IconUri $nuspecxml.package.metadata.iconUrl `
  -LicenseUri $nuspecxml.package.metadata.licenseUrl `
  -ReleaseNotes $nuspecxml.package.metadata.releaseNotes `
  -Tags $nuspecxml.package.metadata.tags `
  -RequiredVersion $module.Version `
  -NuGetApiKey $nugetApiKey `
  -Confirm:$false;
```

see the Scriplet repo for the complete script

I noticed the following things:

1. the first time I ran this, it asked me to include NuGet in the path , maybe we have to install this manually on TC (specifying the confirm switch did not help)
1. if you publish a module that has dependencies that are *NOT* on PowerShellGallery, then publishing fails
1. we get a warning that Tags, ReleaseNotes, ... are not defined in PSD1 but are now supported --- we should include these tags in the PSD1 as well and feed the nuspec from it to eliminate redundancy

> WARNING: Tags are now supported in the module manifest file (.psd1). Update the module manifest file of module 'biz.dfch.PS.System.Logging' in 'C:\ProgramFiles\WindowsPowerShell\Modules\biz.dfch.PS.System.Logging\1.4.1.20160715' with the newest tag changes. You can run Update-ModuleManifest -Tags to update the manifest with tags.
> WARNING: ReleaseNotes is now supported in the module manifest file (.psd1). Update the module manifest file of module 'biz.dfch.PS.System.Logging' in 'C:\ProgramFiles\WindowsPowerShell\Modules\biz.dfch.PS.System.Logging\1.4.1.20160715' with the newest ReleaseNotes changes. You can run Update-ModuleManifest -RleaseNotes to update the manifest withReleaseNotes.
> WARNING: LicenseUri is now supported in the module manifest file (.psd1). Update the module manifest file of module 'biz.dfch.PS.System.Logging' with the newest LicenseUri changes. You canrun Update-ModuleManifest -LicenseUri to update the manifest with LicenseUri.
> WARNING: IconUri is now supported in the module manifest file (.psd1). Update the module manifest file of module 'biz.dfch.PS.System.Logging' in 'C:\ProgramFiles\WindowsPowerShell\Modules\biz.dfch.PS.System.Logging\1.4.1.20160715' with the newest IconUri changes. You can run Update-ModuleManifest -IconUri to update the manifest with IconUri.
> WARNING: This module 'C:\Users\Administrator\AppData\Local\Temp\1077419860\biz.dfch.PS.System.Logging\biz.dfch.PS.System.Logging.psd1' has exported functions. As a best practice, includeexported functions in the module manifest file(.psd1). You can run Update-ModuleManifest -FunctionsToExport to update the manifest with ExportedFunctions field.

**Comment by rufer7** [comment]
```Posh
try 
{
	cd %system.PackageDeployOutput%;

	$nupkgFileName = Get-ChildItem -Filter *.nupkg -Name;
	$zipFileName = '{0}.zip' -f $nupkgFileName;
	Rename-Item $nupkgFileName $zipFileName;
	Expand-Archive $zipFileName;
	Push-Location $nupkgFileName;

        # Install module
        .\Install.ps1;
	Push-Location tools;
	$pathToPsd1 = (Get-ChildItem *.psd1 -File | Select -First 1).FullName;
        $psd1 = Test-ModuleManifest $pathToPsd1;

        $module = Get-Module $psd1.Name -ListAvailable;
	$module | Publish-Module -NuGetApiKey %NuGetApiKey% -Confirm:$false;
} 
catch 
{
	Write-Host "##teamcity[buildStatus status='FAILURE' text='Publish module to PowerShellGallery.com FAILED']";
	#$teamcityErrorMessage = '##teamcity[message text="{0}"]' -f $_.Exception.Message;
	$teamcityErrorMessage = $_.Exception.Message;
	Write-Host $teamcityErrorMessage;
}
finally
{
        # Uninstall module
        $pathToDelete = "{0}{1}" -f $module.Path, "\..\..\..";
        cd $pathToDelete;
        Remove-Item $module.Name -Force -Recurse;
}
```

**Comment by stevenpi** [comment]
Finally configured the build server.
Checked with marc.
