### ISSUE TITLE
Fix findings of PSScriptAnalyzer

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.PS.Appclusive.Client#35]
**TODOs**
* [x] Scan the following repositories without specific `Severity` (If no severity specified, findings of all severities are shown: *Information*, *Warning*, *Error*)
  * [x] [biz.dfch.PS.Appclusive.Client](https://github.com/dfensgmbh/biz.dfch.PS.Appclusive.Client)
  * [x] [biz.dfch.PS.Appclusive.Setup](https://github.com/dfensgmbh/biz.dfch.PS.Appclusive.Setup)
* [x] Fix/supress findings
  * [x] [biz.dfch.PS.Appclusive.Client](https://github.com/dfensgmbh/biz.dfch.PS.Appclusive.Client)
  * [x] [biz.dfch.PS.Appclusive.Setup](https://github.com/dfensgmbh/biz.dfch.PS.Appclusive.Setup)
* [x] Check, if it's possible to exclude some findings like the ones in New-ManagementCredential as the username and password parameters are inteded to be there

For more details concerning `Invoke-ScriptAnalyzer` see [here](https://technet.microsoft.com/de-de/library/dn948237.aspx)

**Comment by dfch** [comment]
I would actually scan additionally with `Severity` *Information*:

> Invoke-ScriptAnalyzer -Severity Information

``` powershell
RuleName                            Severity     FileName   Line  Message
--------                            --------     --------   ----  -------
PSProvideCommentHelp                Information  Get-Sessio 1     The cmdlet 'Get-SessionTenant' does not have a help comment.
                                                 nTenant.ps
                                                 1
PSProvideCommentHelp                Information  Get-Time.p 1     The cmdlet 'Get-Time' does not have a help comment.
                                                 s1
PSProvideCommentHelp                Information  Remove-Man 1     The cmdlet 'Remove-ManagementCredential' does not have a
                                                 agementCre       help comment.
                                                 dential.ps
                                                 1
PSProvideCommentHelp                Information  Remove-Nod 1     The cmdlet 'Remove-Node' does not have a help comment.
                                                 e.ps1
PSProvideCommentHelp                Information  Set-Sessio 1     The cmdlet 'Set-SessionTenant' does not have a help comment.
                                                 nTenant.ps
                                                 1
```

**Comment by dfch** [comment]
we should suppress certain message such as ClearTextPassword as described here https://github.com/PowerShell/PSScriptAnalyzer#suppressing-rules

**Comment by rufer7** [comment]
@dfch added SuppressMessage attributes to disable PoSH ScriptAnalyzer warnings

See commit 1ba70f462389da64d9f406bd4d66468e9d641470

**Comment by stevenpi** [comment]
To export ScriptAnalyzers data:

just pipe | Out-File behind the command. Here an Example:
'''PoSh
Invoke-ScriptAnalyzer -Path PATH -Recurse | Out-File PATH_TO_TXT_FILE
'''
the '-Recurse' argument stands for searching for scripts in every subfolder.

**Comment by rufer7** [comment]
@stevenpi and me fixed nearly all the findings expect the following ones as we were not sure, if we should fix them or not.

**\src**
```Posh
RuleName                            Severity     FileName   Line  Message
--------                            --------     --------   ----  -------
PSUseToExportFieldsInManifest       Warning      biz.dfch.P 199   Do not use wildcard or $null in this field. Explicitly
                                                 S.Appclusi       specify a list for FunctionsToExport.
                                                 ve.Client.
                                                 psd1
PSUseToExportFieldsInManifest       Warning      biz.dfch.P 202   Do not use wildcard or $null in this field. Explicitly
                                                 S.Appclusi       specify a list for CmdletsToExport.
                                                 ve.Client.
                                                 psd1
PSUseToExportFieldsInManifest       Warning      biz.dfch.P 208   Do not use wildcard or $null in this field. Explicitly
                                                 S.Appclusi       specify a list for AliasesToExport.
                                                 ve.Client.
                                                 psd1
PSAvoidUsingInvokeExpression        Warning      biz.dfch.P 35    Invoke-Expression is used. Please remove Invoke-Expression
                                                 S.Appclusi       from script and find other options instead.
                                                 ve.Client.
                                                 psm1
PSAvoidUsingPlainTextForPassword    Warning      Enter-Serv 62    Parameter '$Credential' should use SecureString, otherwise
                                                 er.ps1           this will expose sensitive information. See
                                                                  ConvertTo-SecureString for more information.
PSUsePSCredentialType               Warning      Enter-Serv 1     The Credential parameter in 'Enter-Server' must be of type
                                                 er.ps1           PSCredential. For PowerShell 4.0 and earlier, please define
                                                                  a credential transformation attribute, e.g.
                                                                  [System.Management.Automation.Credential()], after the
                                                                  PSCredential type attribute.
PSUseShouldProcessForStateChangingF Warning      Install.ps 68    Function ’Update-Directory’ has verb that could change
unctions                                         1                system state. Therefore, the function has to support
                                                                  'ShouldProcess'.
```

The following findings were ignored because the ones concerning `svc` only occur in test skeleton scripts and the `PSUseShouldProcessForStateChangingFunctions` findings will disappear as soon as the corresponding functions will be replaced by separate Cmdlets

```Posh
RuleName                            Severity     FileName   Line  Message
--------                            --------     --------   ----  -------
PSUseShouldProcessForStateChangingF Warning      Acl_Ace.ps 68    Function ’Update-Acl’ has verb that could change
unctions                                         1                system state. Therefore, the function has to support
                                                                  'ShouldProcess'.
PSUseShouldProcessForStateChangingF Warning      Acl_Ace.ps 187   Function ’Update-Ace’ has verb that could change
unctions                                         1                system state. Therefore, the function has to support
                                                                  'ShouldProcess'.
PSUseShouldProcessForStateChangingF Warning      Assoc.ps1  47    Function ’Update-Assoc’ has verb that could change
unctions                                                          system state. Therefore, the function has to support
                                                                  'ShouldProcess'.
PSUseShouldProcessForStateChangingF Warning      Cart.ps1   79    Function ’Update-CartItem’ has verb that could
unctions                                                          change system state. Therefore, the function has to
                                                                  support 'ShouldProcess'.
PSUseShouldProcessForStateChangingF Warning      CatalogueA 158   Function ’Update-Catalogue’ has verb that could
unctions                                         ndCatalogu       change system state. Therefore, the function has to
                                                 eItems.ps1       support 'ShouldProcess'.
PSUseShouldProcessForStateChangingF Warning      CatalogueA 190   Function ’Update-CatalogueItem’ has verb that could
unctions                                         ndCatalogu       change system state. Therefore, the function has to
                                                 eItems.ps1       support 'ShouldProcess'.
PSUseDeclaredVarsMoreThanAssigments Warning      ContractMa 29    The variable 'svc' is assigned but never used.
                                                 pping.Test
                                                 s.ps1
PSUseDeclaredVarsMoreThanAssigments Warning      CostCentre 29    The variable 'svc' is assigned but never used.
                                                 .Tests.ps1
PSUseDeclaredVarsMoreThanAssigments Warning      Customer.T 29    The variable 'svc' is assigned but never used.
                                                 ests.ps1
PSUseDeclaredVarsMoreThanAssigments Warning      EntityKind 29    The variable 'svc' is assigned but never used.
                                                 MaterialMa
                                                 pping.Test
                                                 s.ps1
PSUseShouldProcessForStateChangingF Warning      ExternalNo 47    Function ’Update-ExternalNode’ has verb that could
unctions                                         de.ps1           change system state. Therefore, the function has to
                                                                  support 'ShouldProcess'.
PSUseShouldProcessForStateChangingF Warning      ExternalNo 88    Function ’Update-ExternalNodeBag’ has verb that
unctions                                         de.ps1           could change system state. Therefore, the function
                                                                  has to support 'ShouldProcess'.
PSUseShouldProcessForStateChangingF Warning      Folder.ps1 38    Function ’Update-Folder’ has verb that could change
unctions                                                          system state. Therefore, the function has to support
                                                                  'ShouldProcess'.
PSUseDeclaredVarsMoreThanAssigments Warning      Gate.Tests 29    The variable 'svc' is assigned but never used.
                                                 .ps1
PSUseDeclaredVarsMoreThanAssigments Warning      Job.Tests. 29    The variable 'svc' is assigned but never used.
                                                 ps1
PSUseDeclaredVarsMoreThanAssigments Warning      Management 30    The variable 'svc' is assigned but never used.
                                                 Credential
                                                 .Tests.ps1
PSUseDeclaredVarsMoreThanAssigments Warning      Management 29    The variable 'svc' is assigned but never used.
                                                 Uri.Tests.
                                                 ps1
PSUseShouldProcessForStateChangingF Warning      Product.ps 84    Function ’Update-Product’ has verb that could change
unctions                                         1                system state. Therefore, the function has to support
                                                                  'ShouldProcess'.
PSUseDeclaredVarsMoreThanAssigments Warning      Tenant.Tes 28    The variable 'svc' is assigned but never used.
                                                 ts.ps1
PSUseDeclaredVarsMoreThanAssigments Warning      User.Tests 28    The variable 'svc' is assigned but never used.
                                                 .ps1
```
