### ISSUE TITLE
Implement EntityBag Cmdlets

### ISSUE THREAD

**Issue by gitsalles** [dfensgmbh/biz.dfch.PS.Appclusive.Client#44]
Implement `EntityBag` Cmdlets

**TODOs**
* [x] Pester tests for `Set-EntityBag`
  * [x] Create new EntityBag
  * [x] Update `Description`
  * [x] Update `Value`
  * [x] Update `ProtectionLevel` (Parameter set)
* [x] `Set-EntityBag`
  * [x] Parameter validation in general using PowerShell annotations and `Contract-Assert`
  * [x] Validate `EntityKindId` to not be 0 if passed
  * [x] Check, if `EntityKind` exists if `EntityKindId` passed
  * [x] Parameter validation for strings where it makes sense (`[ValidateNotNullOrEmpty()]`)
* [x] Pester tests for `New-EntityBag`
  * [x] Create new EntityBag with required properties (`Name`, `EntityKindId`, `EntityId`, `Value`) -> Verify that protection level is set to Default (Use constants from Public project - `[biz.dfch.CS.Appclusive.Public.OdataServices.Core.EntityBagProtectionLevelEnum]::Default.value__`)
  * [x] Create new EntityBag with protection level (`Name`, `EntityKindId`, `EntityId`, `Value`, `ProtectionLevel`)
  * [x] Create new EntityBag with description (`Name`, `EntityKindId`, `EntityId`, `Value`, `Description`)
* [x] `New-EntityBag`
  * [x] Parameter validation for strings where it makes sense (`[ValidateNotNullOrEmpty()]`)
  * [x] Parameter validation in general using PowerShell annotations and `Contract-Assert`
* [x] Pester tests for `Get-EntityBag`
  * [x] Get EntityBag by `Id`
  * [x] Get EntityBags by `Name`
  * [x] Get EntityBags by `EntityKindId` and `EntityId`
  * [x] Get EntityBags by `Name`, `EntityKindId` and `EntityId`
* [x] `Get-EntityBag`
  * [x] Parameter validation for strings where it makes sense (`[ValidateNotNullOrEmpty()]`)
  * [x] Parameter validation in general using PowerShell annotations and `Contract-Assert`

**IMPORTANT**
* `Value` can be an empty string!
* [x] Add Cmdlets to the following files
  * [x] .nuspec
  * [x] .psd1
* [x] Add Apache 2 license body to all newly created `.ps1` files
* [x] @rufer7 - Update release notes accordingly

**Comment by rufer7** [comment]
@dfch is it possible having more than one `EntityBag` with the same name that belongs to the same entity? First implementation of the `Set-EntityBag` Cmdlet searches for an already existing `EntityBag` based on the `Name`, `EntityId` and `EntityKindId` as shown below

```PoSH
	$exp = @();
	
	$exp += ("(tolower(Name) eq '{0}')" -f $Name.ToLower());
	$exp += ("(EntityId eq {0})" -f $EntityId);
	$exp += ("(EntityKindId eq {0})" -f $EntityKindId);

	$FilterExpression = [String]::Join(' and ', $exp);

	$entity = $svc.Core.EntityBags.AddQueryOption('$filter', $FilterExpression).AddQueryOption('$top',1) | Select;
```

**Comment by dfch** [comment]
@rufer7 there can always be only a single EntityBag entity per entity id.

**Comment by rufer7** [comment]
@stevenpi for your info. @dfch and me decided to not implement `Remove-EntityBag` Cmdlet as deletion is already possible via `Remove-Entity.ps1`. 

I already removed the two files `Remove-EntityBag.ps1` and `Remove-Entity.Bag.Tests.ps1` from the feature branch

**Comment by rufer7** [comment]
According discussion with @dfch and @stevenpi we decided to implement BaseDto support as soon as we have a concrete scenario
