### ISSUE TITLE
Improve Validation in Set- and New-MangementUri Cmdlets

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.PS.Appclusive.Client#80]
Validaiton in `Set-ManagementUri` and `New-ManagementUri` Cmdlets has to be improved

**TODOs**
* [x] `Set-ManagementUri`
  * [x] Validate `ManagementCredentialId` to not be 0 if passed
* [x] `New-ManagementUri`
  * [x] Validate `ManagementCredentialId` to not be 0 if passed
  * [x] Check, if `ManagementCredential` exists if `ManagementCredentialId` is passed
* [x] Write tests to verify validation
